name: MongoDB Backup

on:
  workflow_dispatch:

jobs:
  mongodb-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config

      - name: Create MongoDB backup
        run: |
          kubectl exec -n production mongodb-0 -- sh -c "mongodump --archive --gzip" > mongodb-backup-${{ github.run_number }}.gz
          ls -lh mongodb-backup-${{ github.run_number }}.gz

      - name: Upload MongoDB backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: mongodb-backup-${{ github.run_number }}
          path: mongodb-backup-${{ github.run_number }}.gz